### ISSUE TITLE
example node-microphone not working on MacOS Catalina

### ISSUE THREAD

**Issue by akshay772** [jaxcore/jaxcore-speech#11]
created
TensorFlow: v1.14.0-21-ge77504ac6b
DeepSpeech: v0.6.0-0-g6d43e21
2019-12-21 15:15:21.046395: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Press Ctrl-C to exit at any time.

Press ENTER to start recording.
 I am getting the following error. 

Press ENTER to stop.
.s
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by dsteinman** [comment]
I assume you're using Windows?  I've just made a change to the code to force it to use the "sox" program to record the audio.  Could you do a `git pull` and install this:

http://sox.sourceforge.net/

**Comment by dsteinman** [comment]
(Sorry my last response I didn't read the title)

I haven't upgraded to Catalina yet but plan to soon so I can't be sure if it's just your environment or a bug in this code.

FYI I've massively rearranged this code base and renamed the project.  There are some new web-based demos now.  The previous examples aren't working in the codebase yet.

**Comment by dsteinman** [comment]
I finally got around to upgrading to Catalina, and it everything is still working for me.

Were you able to get it working?  Did you try any of the examples at https://github.com/mozilla/DeepSpeech-examples ?
